createConsoleInterface = (context) ->
  log: (args...) ->
    context.emit 'console-message', 'log', args...
  info: (args...) ->
    context.emit 'console-message', 'info', args...
  warn: (args...) ->
    context.emit 'console-message', 'warn', args...
  error: (args...) ->
    context.emit 'console-message', 'error', args...

module.exports = {createConsoleInterface}

